### PR TITLE
Nov 15 Update

### PR DESCRIPTION
**Pull request by bountygiver**
Hotfix:
- Fixed schematic patch exclusions are not properly read from the config file
- Recover dead soldier's items on wave end (and remove their bodies)
- Properly reset all unit internal ability counters (Such as SPARK's Nova damage stacks)
- Unconscious soldiers now wakes up on wave end.

### CODE REVIEW

**Comment by bountygiver** [comment]
the changes in WaveCOMStrategy.uc should have no effect for now, it is made to handle potential score screen implementation in the future.

**Comment by bountygiver** [comment]
- Properly remove dead soldiers from squad 
- Support new way to add bonus ammo (from June patch), also added refill ammo support on hunter's axe
- Fixed Nov8 Update causing avenger shortcut to appear 
- Hide preparation panel if loaded a game in combat phase 
- Fixed a bug where upgrading items cause deploy soldier to stop working, now if you purchase a spark and has no spawn location, you can click the deploy button again after freeing the spawn point to bring the spark to the game for free (you already paid for it earlier) 
- Fixed various UI performance issues, now you also can no longer tab to different soldiers in loadout screen which previously causes unexpected behaviour (#2)

**Comment by bountygiver** [comment]
- Added Black Market and OTS
- Fixed a bug where you lose soldier's equipment that promoted to squaddie
- Fixed a bug where SPARKs are not counted as avenger crews (For items upgrade purpose)
- Intel now comes into play, removes free elerium core per round and replaced with intel (you can buy elerium cores in black market), supplies per kill also no longer grant you the corpse's price as you have now access to the black market.

**Comment by bountygiver** [comment]
- Cleared WaveCOMMissionSource.uc  of useless functions
- Now refill inventory items for all soldiers automatically on preparation round (You used to need to enter and exit loadout)
- Made WaveCOM_UILoadoutButton.uc a UIPanel instead of UIScreenListener to fix some crash/black screen issues
- Fixed OTS captain perks not working properly
- Added a console command to generate a new map (you keep all your progression). If you have more units than your spawn points allowed, they will be not deployed initially on the next map, but you may deploy them for free once you cleared out the spawn zone using the deploy soldiers button. (#4 we will need to implement a UI for this)

**Comment by bountygiver** [comment]
- Added purchasable continent bonuses 
- Added psi training

**Comment by bountygiver** [comment]
- Fixed multiple events stacking bug (Event listeners now gets cleaned up routinely, this also cleans up dead alien's event listener which improves performance of doing anything)
- WaveCOM can now spawn chryssalids, berserkers, sectopods and gatekeepers, also added a special chryssalid wave.
- Fixed gremlins not created properly, causing SPARK's heavy weapons to fire from middle of the map.
- Fixed item images not loading properly

**Comment by MalucoMarinero** [comment]
Cheers for all this. Merging. Little late but work + moving house has kept me off anything modding related for a little while.

**Pull request merged**
